site_name: pygeoapi
site_description: "pygeoapi: an OGC API to geospatial data"
site_author: the pygeoapi community
copyright: Copyright (c) 2019 Tom Kralidis
site_url: https://pygeoapi.io
repo_url: https://github.com/geopython/pygeoapi.io
docs_dir: docs

nav:
    - Home: index.md
    - Community: community/index.md
    - Docs: https://docs.pygeoapi.io
    - Presentations: presentations/index.md
    - Demo: https://demo.pygeoapi.io
    - Code: https://github.com/geopython/pygeoapi
    - Development: development/index.md

use_directory_urls: true

theme: yeti

plugins:
    - search

